### ISSUE TITLE
Products: Se debe crear categorias

### ISSUE THREAD

**Issue by Humberto-dev** [WTFGurus/base#1]
Para crear un producto, primero se debe crear una categoria.

**Comment by Pheetbag** [comment]
Debido al funcionamiento de las categorías en el eshop no hay problema con dejar productos sin categorías, solamente deben tener en cuenta que el mismo no se mostrará en la tienda hasta que no se le asigne ninguna categoría.

Para fines de claridad se le agregó al index de producto la palabra "uncategorized". Anteriormente se mostraba vacío.
