### ISSUE TITLE
Rol: Campos vacios con problemas

### ISSUE THREAD

**Issue by Humberto-dev** [WTFGurus/base#3]
Add Role y  Edit Role: Permite dejar ingresar registros con campos en blanco generando problemas para eliminar o editar. Campos deben ser requeridos

**Comment by Pheetbag** [comment]
Ya no se pueden guardar ni editar roles dejando campos vacíos, además se hicieron obligatorios en la base de datos (al menos el campo name para los slugs). Sigue generando problemas al eliminarlos, pues la base de datos rechaza los intentos de eliminar registros que tienen alguno refiriendose a esa id. si hay usuarios registrados con ese rol se rechaza el intento de borrar. (En el futuro hay que definir mensajes de error mucho mejor elaborados)
