### ISSUE TITLE
new rol: Enlace no funciona

### ISSUE THREAD

**Issue by Humberto-dev** [WTFGurus/base#4]
Product details/ Add new: no funciona el enlace

**Comment by Pheetbag** [comment]
El enlace aparentemente se encuentra funcionando (se mencionan dos enlaces en el issue, ambos están funcionando sin problemas)

Aún así aprovecho la oportunidad para decir que las urls para editar los productos estan corregidas, se mostraban de la forma: 

http://hairlocshub.io/product/edit/?slug=complete-kit

ahora aparecen como 

http://hairlocshub.io/product/edit/complete-kit
