### ISSUE TITLE
Category: no permite actualizar

### ISSUE THREAD

**Issue by Humberto-dev** [WTFGurus/base#6]
category-product/update/tools/: al intentar actualizar una categoria presenta error

**Comment by Pheetbag** [comment]
Solucionado los problemas de actualización de la categoría, se debia a que la route requeria que el metodo para hacer match fuese de tipo get, esto esta bien para mostrar una pagina de editar, pero cuando el formulario se envia el metodo por lo general suele ser post o put, por lo que agrego estos otros metodos a la compatibilidad de la route, de esta forma hace match con la ruta adecuada y puede actualizar el producto.
