### ISSUE TITLE
Tienda: mensaje de producto no existente

### ISSUE THREAD

**Issue by shinshadows** [WTFGurus/base#8]
Se debe crear un alerta para los productos que no poseen un estilo en existencia

Se genera un error , en el momento que el cliente agrega al carrito de compra, ya que el producto no existe  para el estilo.

**Comment by Pheetbag** [comment]
Esto fue solucionado hace un tiempo, los productos filtran adecuadamente el tema de los estilos y los colores, tanto en el carrito como en el purchase y la vista de los productos.
